### ISSUE TITLE
Activating 2fa on spark results in error

### ISSUE THREAD

**Issue by magelfik** [cretueusebiu/laravel-spark-google2fa#17]
Apparently, I need to activate something, though I am not sure on how to do that. The error is
```
It's not secure to send secret keys to Google Apis, you have to explicitly allow it by calling $google2fa->setAllowInsecureCallToGoogleApis(true).
```

Where am I supposed to enable this ? Is it a normal behaviour ?
Thanks for the answer.

**Comment by cretueusebiu** [comment]
I see this was introduced with v3. Not sure why it's not installing v2, since that's what's in composer.json. 

It seems that the new version requires you to call that method:
https://github.com/antonioribeiro/google2fa#show-the-qr-code-to-your-user-via-google-apis

If you make those changes and submit a PR would be great.

**Comment by magelfik** [comment]
That should do it : https://github.com/cretueusebiu/laravel-spark-google2fa/pull/18

**Comment by magelfik** [comment]
Hey there, I see my PR hasn't been accepted yet. Is there something wrong ?

Thanks in advance for your response.

**Comment by cretueusebiu** [comment]
Merged and released!
